services:
  whatsapp-bot: #for coolify
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 10s
    volumes:
      - /auth:/app/auth
    env_file:
      - .env
    ports:
      - '3000:3000'
  whatsapp-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot-dev
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '3000:3000'
